### ISSUE TITLE
incorrect exports/opens

### ISSUE THREAD

**Issue by xenoterracide** [asciidoctor/asciidoclet#142]
I believe this is the correct list for java 21

```kts
    jFlags = listOf(
      "--add-exports=jdk.javadoc/jdk.javadoc.internal.tool=ALL-UNNAMED",
      "--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED",
      "--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED",
      "--add-opens=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED",
      "--add-opens=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED",
    )
```    

```
error: fatal error encountered: java.lang.IllegalAccessError: superclass access check failed: class org.asciidoctor.asciidoclet.AsciidoctorFilteredEnvironment (in unnamed module @0x4535b6d5) cannot access class jdk.javadoc.internal.tool.DocEnvImpl (in module jdk.javadoc) because module jdk.javadoc does not export jdk.javadoc.internal.tool to unnamed module @0x4535b6d5
error: Please file a bug against the javadoc tool via the Java bug reporting page
  (https://bugreport.java.com) after checking the Bug Database (https://bugs.java.com)
  for duplicates. Include error messages and the following diagnostic in your report. Thank you.
java.lang.IllegalAccessError: superclass access check failed: class org.asciidoctor.asciidoclet.AsciidoctorFilteredEnvironment (in unnamed module @0x4535b6d5) cannot access class jdk.javadoc.internal.tool.DocEnvImpl (in module jdk.javadoc) because module jdk.javadoc does not export jdk.javadoc.internal.tool to unnamed module @0x4535b6d5
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at org.asciidoctor.asciidoclet.Asciidoclet.run(Asciidoclet.java:217)
        at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:575)
        at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:398)
        at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:347)
        at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:57)
        at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:46)
```

using java 21.

```
--attribute 'name=semver,version=0.0.0'
--base-dir '/home/xeno/IdeaProjects/gradle-semver/module/semver'
-classpath '/home/xeno/IdeaProjects/gradle-semver/module/semver/build/classes/java/main:/home/xeno/IdeaProjects/gradle-semver/module/semver/build/resources/main:/home/xeno/.gradle/caches/8.11.1/generated-gradle-jars/gradle-api-8.11.1.jar:/home/xeno/.gradle/wrapper/dists/gradle-8.11.1-bin/bpt9gzteqjrbo1mjrsomdt32c/gradle-8.11.1/lib/groovy-3.0.22.jar:/home/xeno/.gradle/wrapper/dists/gradle-8.11.1-bin/bpt9gzteqjrbo1mjrsomdt32c/gradle-8.11.1/lib/groovy-ant-3.0.22.jar:/home/xeno/.gradle/wrapper/dists/gradle-8.11.1-bin/bpt9gzteqjrbo1mjrsomdt32c/gradle-8.11.1/lib/groovy-astbuilder-3.0.22.jar:/home/xeno/.gradle/wrapper/dists/gradle-8.11.1-bin/bpt9gzteqjrbo1mjrsomdt32c/gradle-8.11.1/lib/groovy-console-3.0.22.jar:/home/xeno/.gradle/wrapper/dists/gradle-8.11.1-bin/bpt9gzteqjrbo1mjrsomdt32c/gradle-8.11.1/lib/groovy-datetime-3.0.22.jar:/home/xeno/.gradle/wrapper/dists/gradle-8.11.1-bin/bpt9gzteqjrbo1mjrsomdt32c/gradle-8.11.1/lib/groovy-dateutil-3.0.22.jar:/home/xeno/.gradle/wrapper/dists/gradle-8.11.1-bin/bpt9gzteqjrbo1mjrsomdt32c/gradle-8.11.1/lib/groovy-groovydoc-3.0.22.jar:/home/xeno/.gradle/wrapper/dists/gradle-8.11.1-bin/bpt9gzteqjrbo1mjrsomdt32c/gradle-8.11.1/lib/groovy-json-3.0.22.jar:/home/xeno/.gradle/wrapper/dists/gradle-8.11.1-bin/bpt9gzteqjrbo1mjrsomdt32c/gradle-8.11.1/lib/groovy-nio-3.0.22.jar:/home/xeno/.gradle/wrapper/dists/gradle-8.11.1-bin/bpt9gzteqjrbo1mjrsomdt32c/gradle-8.11.1/lib/groovy-sql-3.0.22.jar:/home/xeno/.gradle/wrapper/dists/gradle-8.11.1-bin/bpt9gzteqjrbo1mjrsomdt32c/gradle-8.11.1/lib/groovy-templates-3.0.22.jar:/home/xeno/.gradle/wrapper/dists/gradle-8.11.1-bin/bpt9gzteqjrbo1mjrsomdt32c/gradle-8.11.1/lib/groovy-test-3.0.22.jar:/home/xeno/.gradle/wrapper/dists/gradle-8.11.1-bin/bpt9gzteqjrbo1mjrsomdt32c/gradle-8.11.1/lib/groovy-xml-3.0.22.jar:/home/xeno/.gradle/wrapper/dists/gradle-8.11.1-bin/bpt9gzteqjrbo1mjrsomdt32c/gradle-8.11.1/lib/javaparser-core-3.17.0.jar:/home/xeno/.gradle/wrapper/dists/gradle-8.11.1-bin/bpt9gzteqjrbo1mjrsomdt32c/gradle-8.11.1/lib/kotlin-stdlib-2.0.20.jar:/home/xeno/.gradle/wrapper/dists/gradle-8.11.1-bin/bpt9gzteqjrbo1mjrsomdt32c/gradle-8.11.1/lib/kotlin-reflect-2.0.20.jar:/home/xeno/.gradle/wrapper/dists/gradle-8.11.1-bin/bpt9gzteqjrbo1mjrsomdt32c/gradle-8.11.1/lib/gradle-installation-beacon-8.11.1.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/org.eclipse.jgit/org.eclipse.jgit/7.0.0.202409031743-r/e11135ded2f1f78da9a028002ad7837cc970ee8e/org.eclipse.jgit-7.0.0.202409031743-r.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/org.semver4j/semver4j/5.4.1/cbb3390848920403e16e4ca9e12996d39f586509/semver4j-5.4.1.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/33.3.1-jre/852f8b363da0111e819460021ca693cacca3e8db/guava-33.3.1-jre.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/com.google.errorprone/error_prone_annotations/2.36.0/227d4d4957ccc3dc5761bd897e3a0ee587e750a7/error_prone_annotations-2.36.0.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/org.jspecify/jspecify/1.0.0/7425a601c1c7ec76645a78d22b8c6a627edee507/jspecify-1.0.0.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/io.vavr/vavr/0.10.5/e2adc49979a4597ceabbcd63c83fcd0323b7bba3/vavr-0.10.5.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.36/6c62681a2f655b49963a5983b8b0950a6120ae14/slf4j-api-1.7.36.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/com.xenoterracide/tools/0.1.0-beta.1/e2d3d11b228282fb2a3f37a045fb4d2fd0bf2d1/tools-0.1.0-beta.1.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/org.checkerframework/checker-qual/3.43.0/9425eee39e56b116d2b998b7c2cebcbd11a3c98b/checker-qual-3.43.0.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/com.google.guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/b421526c5f297295adef1c886e5246c39d4ac629/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/com.google.j2objc/j2objc-annotations/3.0.0/7399e65dd7e9ff3404f4535b2f017093bdb134c7/j2objc-annotations-3.0.0.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/io.vavr/vavr-match/0.10.5/cc8937f425be41341d2d998a0eeff037ca1efd2d/vavr-match-0.10.5.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/com.google.guava/failureaccess/1.0.2/c4a06a64e650562f30b7bf9aaec1bfed43aca12b/failureaccess-1.0.2.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/com.google.code.findbugs/jsr305/3.0.2/25ea2e8b0c338a877313bd4672d3fe056ea78f0d/jsr305-3.0.2.jar'
-d '/home/xeno/IdeaProjects/gradle-semver/module/semver/build/docs/javadoc'
-doclet 'org.asciidoctor.asciidoclet.Asciidoclet'
-docletpath '/home/xeno/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoclet/2.0.0/103684cb68059650adbbb65f3bec8c8ae4b11713/asciidoclet-2.0.0.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj/2.5.12/3d8ab4c6f2d462cf44055c5a1ee6f4bf8b8839ef/asciidoctorj-2.5.12.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/com.beust/jcommander/1.82/a7c5fef184d238065de38f81bbc6ee50cca2e21/jcommander-1.82.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/org.asciidoctor/asciidoctorj-api/2.5.12/f5a64200f5066c1879c79f520aa3a89c5bf66561/asciidoctorj-api-2.5.12.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/org.jruby/jruby/9.4.6.0/ccc9de5e80701cfe00bce45ac78448fc09c1d9b4/jruby-9.4.6.0.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-base/9.4.6.0/da806c0e5eee1ff98a760b2c166598d3847d1029/jruby-base-9.4.6.0.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-stdlib/9.4.6.0/87bfb1fe802b199517d9ff1bd14a91981968f35f/jruby-stdlib-9.4.6.0.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/com.github.jnr/jnr-ffi/2.2.16/1cf42fc29fed25b44710a52e03a45f11d4f823d5/jnr-ffi-2.2.16.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-commons/9.2/f4d7f0fc9054386f2893b602454d48e07d4fbead/asm-commons-9.2.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-util/9.2/fbc178fc5ba3dab50fd7e8a5317b8b647c8e8946/asm-util-9.2.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-analysis/9.2/7487dd756daf96cab9986e44b9d7bcb796a61c10/asm-analysis-9.2.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-tree/9.2/d96c99a30f5e1a19b0e609dbb19a44d8518ac01e/asm-tree-9.2.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm/9.2/81a03f76019c67362299c40e0ba13405f5467bff/asm-9.2.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/com.github.jnr/jnr-netdb/1.2.0/1bb5527cac7dadaea7c3bd1e3d86dd95ed0d3b87/jnr-netdb-1.2.0.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/com.github.jnr/jnr-unixsocket/0.38.22/d3510478241b9495c0a729471a4f11727d0c794a/jnr-unixsocket-0.38.22.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/com.github.jnr/jnr-enxio/0.32.17/351bb61efa7da082912a1ae5750eae609c8e0dfa/jnr-enxio-0.32.17.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/com.github.jnr/jnr-posix/3.1.19/cc55c9e55541895498acdfd59c3145dff91db6e7/jnr-posix-3.1.19.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/com.github.jnr/jnr-constants/0.10.4/9f6f23763bf40ea7b56391791f574174914430a/jnr-constants-0.10.4.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/com.github.jnr/jffi/1.3.13/861b79314b8cef27f506c007edb78bf1ad0df77c/jffi-1.3.13.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/com.github.jnr/jffi/1.3.13/15e41e9c8f02b384bf138ab7f2778b441bfa5df3/jffi-1.3.13-native.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/org.jruby.joni/joni/2.2.1/23d2f2eff7fa0cda465d86ec9d8bab53e496d9e6/joni-2.2.1.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/org.jruby.jcodings/jcodings/1.0.58/dce27159dc0382e5f7518d4f3e499fc8396357ed/jcodings-1.0.58.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/org.jruby/dirgra/0.3/fcdf20c966ff7bd3299c3d7fb3e7bfb14e38d4ee/dirgra-0.3.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/com.headius/invokebinder/1.13/c0d482bab98c28783d74c0bfff22e93f929b4261/invokebinder-1.13.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/com.headius/options/1.6/ad1647f0b713b8e05b437483573c772d4523a804/options-1.6.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/org.jruby/jzlib/1.1.5/6905026b794aeca0f56758e13b9429b8d6891a5d/jzlib-1.1.5.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/joda-time/joda-time/2.12.5/698ce67b5e58becfb4ef2cf0393422775e59dff4/joda-time-2.12.5.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/me.qmx.jitescript/jitescript/0.4.1/f1efcb28cb13d26faf789264d54251faf58f0b63/jitescript-0.4.1.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/com.headius/backport9/1.13/df081f77e650a562cc821c1590c7cf28a133cef7/backport9-1.13.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/com.github.jnr/jnr-a64asm/1.0.0/a1cb8dbe71b5a6a0288043c3ba3ca64545be165/jnr-a64asm-1.0.0.jar:/home/xeno/.gradle/caches/modules-2/files-2.1/com.github.jnr/jnr-x86asm/1.0.2/6936bbd6c5b235665d87bd450f5e13b52d4b48/jnr-x86asm-1.0.2.jar'
-doctitle 'semver 0.0.0 API'
-notimestamp 
-quiet 
-tag 'apiSpec:a:API Spec:'
-tag 'apiNote:a:API Note:'
-tag 'implSpec:a:Implementation Spec:'
-tag 'implNote:a:Implementation Note:'
-windowtitle 'semver 0.0.0 API'
'/home/xeno/IdeaProjects/gradle-semver/module/semver/src/main/java/com/xenoterracide/gradle/semver/GitStatus.java'
'/home/xeno/IdeaProjects/gradle-semver/module/semver/src/main/java/com/xenoterracide/gradle/semver/internal/package-info.java'
'/home/xeno/IdeaProjects/gradle-semver/module/semver/src/main/java/com/xenoterracide/gradle/semver/internal/AbstractGitService.java'
'/home/xeno/IdeaProjects/gradle-semver/module/semver/src/main/java/com/xenoterracide/gradle/semver/internal/GitMetadata.java'
'/home/xeno/IdeaProjects/gradle-semver/module/semver/src/main/java/com/xenoterracide/gradle/semver/internal/NoGitDirException.java'
'/home/xeno/IdeaProjects/gradle-semver/module/semver/src/main/java/com/xenoterracide/gradle/semver/internal/ProvidedFactory.java'
'/home/xeno/IdeaProjects/gradle-semver/module/semver/src/main/java/com/xenoterracide/gradle/semver/internal/GitMetadataImpl.java'
'/home/xeno/IdeaProjects/gradle-semver/module/semver/src/main/java/com/xenoterracide/gradle/semver/package-info.java'
'/home/xeno/IdeaProjects/gradle-semver/module/semver/src/main/java/com/xenoterracide/gradle/semver/GitMetadataExtension.java'
'/home/xeno/IdeaProjects/gradle-semver/module/semver/src/main/java/com/xenoterracide/gradle/semver/GitMetadataExtensionAdapter.java'
'/home/xeno/IdeaProjects/gradle-semver/module/semver/src/main/java/com/xenoterracide/gradle/semver/GitRemote.java'
'/home/xeno/IdeaProjects/gradle-semver/module/semver/src/main/java/com/xenoterracide/gradle/semver/SemverBuilder.java'
'/home/xeno/IdeaProjects/gradle-semver/module/semver/src/main/java/com/xenoterracide/gradle/semver/SemverPlugin.java'
'/home/xeno/IdeaProjects/gradle-semver/module/semver/src/main/java/com/xenoterracide/gradle/semver/SemverExtension.java'
```

**Comment by abelsromero** [comment]
I am not doubting this, but there's CI testing on Java21 and it's not showing an issue. I'd like to be able to reproduce before introducing changes. Is there anything special in your environment?
